Models/Movie.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Raw_Vidly_App.Models
{
    public class Movie
    {
        public int MovieId { get; set; }
        public string MovieName { get; set; }
        public int Price { get; set; }
        public DateTime ReleaseDate { get; set; }
        public DateTime AddDate { get; set; }
        public int Stock { get; set; }
        [ForeignKey("Genere")]
        public int GenereId { get; set; }
        public Genere Genere { get; set; }
        [ForeignKey("Customers")]
        public int CustomersId { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
        //[ForeignKey("Requests")]
        //public int RequestId { get; set; }
        //public Request Requests { get; set; }

    }
}

Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Microsoft.AspNet.Identity;
using Raw_Vidly_App.Models;

namespace Raw_Vidly_App.Controllers
{
	public class MovieController : Controller
	{
		private RawVidlyDbContext _context;

		public MovieController()
		{
			_context = new RawVidlyDbContext();
		}

		protected override void Dispose(bool disposing)
		{
			_context.Dispose();
		}

		//
		// GET: /Movie/
		public ActionResult ListofMovie()
		{
            List<Movie> movie = _context.Movie.Include(c=>c.Genere).ToList();
			ViewBag.Movies = movie;

            if (User.IsInRole(RoleName.Admin))
                return View("ListofMovie");
             
			return View("ListofMovie_Readonly");
		}
		public ActionResult Details(int id)
		{
		    Movie movie = _context.Movie.Include(c => c.Genere).SingleOrDefault(c => c.MovieId==id);

			return View(movie);
		}
		[HttpGet]
        [Authorize(Roles = RoleName.Admin)]
		public ActionResult AddMovie()
		{
			ViewBag.GenereId = new SelectList(_context.Generes, "GenereId", "GenereName");
			return View();
		}
		[HttpPost]
		public ActionResult AddMovie(Movie movie)
		{
			if (ModelState.IsValid)
			{
				_context.Movie.Add(movie);
				_context.SaveChanges();
			}
			ViewBag.GereneId = new SelectList(_context.Generes, "GenereId", "GenereName",movie.GenereId);


			return RedirectToAction("ListofMovie");
		}

        public ActionResult RequestMovie(RequestViewModel request)
        {
            //_context.Customers.Add(request);
            //_context.SaveChanges();

            return View("ListofMovie_Readonly");
        }
        public ActionResult MovieID(int id)
        {
            Movie movie = _context.Movie.Include(c => c.Customers).SingleOrDefault();
            movie.CustomersId = id;
            
            Customer customer = _context.Customers.SingleOrDefault(c => c.CustomerId==id);
            customer.MoviesId = id;
            _context.Customers.Add(customer);
            _context.SaveChanges();
            return View("ListofMovie_Readonly");
        }

        public ActionResult CustomerMovieId(int mid,int cid)
        {
            //string currentUserId = User.Identity.GetUserId();
            //ApplicationUser currentUser = _context.Users.FirstOrDefault(x => x.Id == currentUserId);
            //IQueryable<Movie> movie = _context.Movie.Include(c => c.MoviesId==mid).Where(m => m.CustomerId == cid);
            //Movie movie = _context.Movie.Include(c => c.Customers);
            //ViewBag.movies = movie;
            //Customer customer = new Customer();
            //var userID = User.Identity.GetUserId();
            //RequestViewModel requestViewModel = new RequestViewModel();
            //requestViewModel.Customer.CustomerId = Convert.ToInt32(userID);
            //customer.CustomerId = cid;
            //customer.MoviesId = mid;
            //requestViewModel.Customer.MoviesId = mid;
            //_context.Movie.Add(movie);
            _context.SaveChanges();
            return View();
        }

        public ActionResult ListOfRent()
        {
            List<Request> request = _context.Requests.ToList();
            ViewBag.Request = request;
            return View("ListofMovie_Readonly");
        }
    }
}

Controllers/RequestController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Raw_Vidly_App.Models;

namespace Raw_Vidly_App.Controllers
{
    public class RequestController : Controller
    {
        private RawVidlyDbContext _context;

        public RequestController()
        {
            _context = new RawVidlyDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        // GET: Request
        public ActionResult ListOfMovie()
        {
            List<Movie> movies = _context.Movie.Include(c => c.Genere).ToList();
            ViewBag.Movies = movies;
            return View();
        }

        public ActionResult RequestMovie(RequestViewModel requestViewModel)
        {
            RequestViewModel request = new RequestViewModel();
            request.Customer.CustomerId = request.CustomersId;
            request.Movie.MovieId = request.MoviesId;
            return View("ListOfMovie");
        }
    }
}

Views/Movie/AddMovie.cshtml
@using Raw_Vidly_App.Models
@model Movie
@{
    ViewBag.Title = "AddMovie";
    Layout = "~/Views/Shared/_Layout.cshtml";
    //List<>
}

<h2>AddMovie</h2>

@using (@Html.BeginForm("AddMovie", "Movie"))
{
    <div>
        @Html.LabelFor(m => m.MovieName)
        @Html.TextBoxFor(m => m.MovieName)
    </div>

    <div>
        @Html.LabelFor(m => m.Genere)
        @Html.DropDownList("GenereId", "Select")
    </div>

    <div>
        @Html.LabelFor(m => m.ReleaseDate)
        @Html.TextBoxFor(m => m.ReleaseDate)
    </div>
    
    <div>
        @Html.LabelFor(m => m.AddDate)
        @Html.TextBoxFor(m => m.AddDate)
    </div>

    <div>
        @Html.LabelFor(m => m.Price)
        @Html.TextBoxFor(m => m.Price)
    </div>

    <div>
        @Html.LabelFor(m => m.Stock)
        @Html.TextBoxFor(m => m.Stock)
    </div>

    <div>
        <input type="submit" value="Save" class="btn btn-success"/>
    </div>
}

Views/Movie/CustomerMovieId.cshtml
@using Raw_Vidly_App.Models
@model RequestViewModel
@{
    ViewBag.Title = "CustomerMovieId";
    List<Movie> Movies = ViewBag.Moviess;

}

<h2>CustomerMovieId</h2>

@{
    <table class="table table-bordered table-hover">
        <thead>
        <tr>
            <th>Name</th>
            <th>Genere</th>
            <th>Price</th>
            <th>Release Date</th>
            <th>Rent</th>
        </tr>
        </thead>
        <tbody>
        
        </tbody>
    </table>

}

Views/Movie/Details .cshtml
@using Raw_Vidly_App.Models

@model Movie
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<h3>@Model.MovieName</h3>
<h4>@Model.ReleaseDate</h4>
<ul>
    <li>@Model.AddDate</li>
    <li>@Model.Genere</li>
    <li>@Model.Price</li>
</ul>

Views/Movie/ListofMovie.cshtml
@using Raw_Vidly_App.Models
@model Raw_Vidly_App.Models.Movie
@{
    ViewBag.Title = "ListofMovie";
    Layout = "~/Views/Shared/_Layout.cshtml";
    List<Movie> Movies = ViewBag.Movies;
}

<h2>ListofMovie</h2>



@{
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Name</th>
                <th>Genere</th>
                <th>Price</th>
                <th>Release Date</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
            @foreach (Movie movies in Movies)
            {
                <tr>
                    <td>@movies.MovieName</td>
                
                    <td>
                        @movies.Genere.GenereName
                    </td>
                
                    <td>@movies.Price</td>
                
                    <td>@movies.ReleaseDate</td>
                
                    <td>
                        @using (Html.BeginForm("ListofMovie", "Movie", new { id = movies.MovieId }))
                        {
                            <input type="submit" value="Delete" class="btn btn-danger" />
                        }
                    </td>
                </tr>

            }
        </tbody>
    </table>

}

Views/Movie/ListofMovie_Readonly.cshtml
@using Microsoft.AspNet.Identity
@using Raw_Vidly_App.Models
@model Raw_Vidly_App.Models.Movie
@{
    ViewBag.Title = "ListofMovie";
    Layout = "~/Views/Shared/_Layout.cshtml";
    List<Movie> Movies = ViewBag.Movies;
    //List<Request> requests = ViewBag.Request;
}

<h2>ListofMovie</h2>

@{
    var id = @Html.HiddenFor(c => c.CustomersId);

}
<p>id</p>
@{
    @Html.HiddenFor(c => c.CustomersId);
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Name</th>
                <th>Genere</th>
                <th>Price</th>
                <th>Release Date</th>
                <th>Rent</th>
            </tr>
        </thead>
        <tbody>
            @foreach (Movie movies in Movies)
            {
                <tr>
                    <td>@movies.MovieName</td>

                    <td>
                        @movies.Genere.GenereName
                    </td>

                    <td>@movies.Price</td>

                    <td>@movies.ReleaseDate</td>

                    <td>

                        @using (Html.BeginForm("CustomerMovieId", "Movie", new { mid = movies.MovieId, cid = movies.CustomerId }))
                        {


                            <input type="submit" value="Rent" class="btn btn-success" />
                        }
                    </td>
                </tr>

            }
        </tbody>
    </table>

}

@{
    @*<table class="table table-bordered table-hover">
        @*<thead>
            <tr>
                <th>Name</th>

            </tr>
        </thead>
        <tbody>*@
    @*@foreach (Request request in requests)
                {
                    <tr>
                        <td>@request</td>



                        <td></td>
                    </tr>

                }
            </tbody>
        </table>*@

}@*@using (Html.BeginForm("RequestMovie", "Request", new {id = movies.MovieId}))
    {
        <input type="submit" value="Rent" class="btn btn-success"/>
    }*@