Controllers/MembershipTypeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Raw_Vidly_App.Models;

namespace Raw_Vidly_App.Controllers
{
	public class MembershipTypeController : Controller
	{
		private RawVidlyDbContext _context;

		public MembershipTypeController()
		{
			_context = new RawVidlyDbContext();
		}

		protected override void Dispose(bool disposing)
		{
		   _context.Dispose();
		}

		//
		// GET: /MembershipType/
        [HttpGet]
		public ActionResult AddmemberType()
        {
            ViewBag.MembershipType = _context.MembershipTypes;
			return View();
		}
        [HttpPost]
        public ActionResult AddmemberType(MembershipType membershipType)
        {
            _context.MembershipTypes.Add(membershipType);
            _context.SaveChanges();
            return RedirectToAction("AddmemberType");
        }

        public ActionResult Delete(int id)
        {
            MembershipType membershipType = _context.MembershipTypes.Find(id);
            _context.MembershipTypes.Remove(membershipType);
            _context.SaveChanges();


            return RedirectToAction("AddmemberType");
        }
	}
}

Views/MembershipType/AddmemberType.cshtml
@using Raw_Vidly_App.Models

@model  MembershipType
@{
    ViewBag.Title = "AddmemberType";
    Layout = "~/Views/Shared/_Layout.cshtml";
    IEnumerable<MembershipType> MembershipType = ViewBag.MembershipType;
}

<h2>AddmemberType</h2>
<table id="member" class="table table-bordered table-hover">
    <thead>
    <tr>
        <th>MemberType Name</th>
        <th>Money</th>
        <th>Action</th>
    </tr>
    </thead>
    <tbody>
    @foreach (MembershipType m in MembershipType)
{
       <tr>

           <td>@m.MembershipName</td>
           <td>coming soon</td>
           <td> @using (Html.BeginForm("Delete", "MembershipType", new { id = m.Id }))
{
    <input type="submit" value="Delete" class="btn btn-default" />
} </td>

    </tr>
 
    
}
    </tbody>
</table>

@using (@Html.BeginForm("AddmemberType", "MembershipType"))
{
    

    <div>
        @Html.TextBoxFor(c => c.MembershipName)
    </div>
    <div>
        <input type="submit" value="Save" />
    </div>
}