Models/Genere.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Raw_Vidly_App.Models
{
    public class Genere
    {
        public int GenereId { get; set; }
        public string GenereName { get; set; }
        public List<Movie> Movie { get; set; }
    }
}

Controllers/GenereController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Raw_Vidly_App.Models;

namespace Raw_Vidly_App.Controllers
{
	public class GenereController : Controller
	{
		private RawVidlyDbContext _context;

		public GenereController()
		{
			_context = new RawVidlyDbContext();
		}

		protected override void Dispose(bool disposing)
		{
			_context.Dispose();
		}


		//
		// GET: /Genere/
        [HttpGet]
		public ActionResult AddGenere()
		{
			ViewBag.Generes = _context.Generes;
			return View();
		}
        [HttpPost]
	    public ActionResult AddGenere(Genere genere)
	    {
	        _context.Generes.Add(genere);
	        _context.SaveChanges();
	        return RedirectToAction("AddGenere");
	    }

	    public ActionResult Delete(int id)
	    {
	        Genere genere = _context.Generes.Find(id);
	        _context.Generes.Remove(genere);
	        _context.SaveChanges();
	        return RedirectToAction("AddGenere");
	    }
	}
}

Views/Genere/AddGenere.cshtml
@using System.Collections
@using Raw_Vidly_App.Models
@model Genere
@{
    ViewBag.Title = "AddGenere";
    Layout = "~/Views/Shared/_Layout.cshtml";
    IEnumerable<Genere> GenereList = ViewBag.Generes;
}

<h2>AddGenere</h2>

<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>Genere Name</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Genere g in GenereList)
        {
            <tr>

                <td>@g.GenereName</td>
                <td>
                    @using (Html.BeginForm("Delete", "Genere", new { id = g.GenereId }))
                    {
                        <input type="submit" value="Delete" class="btn btn-default" />
                    }
                </td>

            </tr>


        }
    </tbody>
</table>

@using (@Html.BeginForm("AddGenere", "Genere"))
{


    <div>
        @Html.TextBoxFor(g=>g.GenereName)
    </div>
    <div>
        <input type="submit" value="Save" />
    </div>
}